#Kaushal Sambhe 22388443 - Operating Systems Project 1
# ca216/myshell
#I declare that this material, which I now submit for assessment,
#is entirely my own work and has not been taken from the work of others
#save and to the extent that such work 
#has been cited and acknowledged within the text of my work.

#Code is from assingment specification
myshell: myshell.c commands.c myshell.h 
	gcc -Wall myshell.c commands.c -o myshell